# OpenAI Configuration for Testing
openai:
  api:
    key: "sk-4a79aae22608494a86e33921b7e1f4c6"
    base-url: "https://api.openai.com/v1"
    model: "gpt-4"
    timeout: 30000
    max-retries: 3
  
  chat:
    temperature: 0.7
    max-tokens: 2000
    top-p: 1.0
    frequency-penalty: 0.0
    presence-penalty: 0.0
  
  image:
    model: "dall-e-3"
    size: "1024x1024"
    quality: "standard"
    n: 1

# Test Configuration
test:
  enabled: true
  environment: "development"
  debug: true
  log-level: "INFO"

# Security Note: This is a test configuration file
# In production, use environment variables or secure key management
security:
  warning: "This file contains sensitive API keys - use only for testing"
  recommendation: "Use environment variables in production"
